### ISSUE TITLE
Exception with meteor 1.3 beta

### ISSUE THREAD

**Issue by d-winter** [poetic/react-autoform-material-ui#9]
Hi, trying to use your package with meteor 1.3 beta 11.
Also tried it with lower 1.3 beta version. Is this issue related to meteor or your package?
Thanks 
Daniel

=> Started proxy.
=> Started MongoDB.

TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at /Users/me/.meteor/packages/meteor-tool/.1.1.13-beta.11.uoh1tu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/mini-files.js:86:16
    at /tools/isobuild/import-scanner.js:87:23
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:86:11)
    at /tools/isobuild/compiler-plugin.js:691:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:672:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:749:8)
    at /tools/isobuild/bundler.js:516:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:507:18)
    at /tools/isobuild/bundler.js:2232:14
    at /tools/isobuild/bundler.js:2322:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/me/.meteor/packages/meteor-tool/.1.1.13-beta.11.uoh1tu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2321:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2213:31)
    at /tools/runners/run-app.js:586:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:576:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:629:35)
    at AppRunner._fiber (/tools/runners/run-app.js:881:28)
    at /tools/runners/run-app.js:406:12

**Comment by JohnRodney** [comment]
@hunius I don't think we've gotten around to testing this package with 1.3.  If this error occurs when you add the package, and goes away when you remove it I would assume we need to update this to 1.3 which we have not gotten around to yet.

Thanks for reporting this.

**Comment by edulix** [comment]
It doesn't work either with meteor 1.4.
